version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sparkles-9router_server_1
      APP_PORT: 20128
      PROXY_AUTH_ADD: "false"

  server:
    image: decolua/9router:0.5.55
    restart: unless-stopped
    environment:
      INITIAL_PASSWORD: batata123!
      DATA_DIR: /app/data
      PORT: 20128
      HOSTNAME: 0.0.0.0
      NODE_ENV: production
      HEADROOM_URL: http://headroom:8787
    depends_on:
      - headroom
    volumes:
      - /home/umbrel/umbrel/app-data/sparkles-9router/data/db:/app/data

  headroom:
    image: ghcr.io/chopratejas/headroom:latest
    restart: unless-stopped
